name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  check:
    strategy:
      matrix:
        node: [">=24"]
        os: [ubuntu-slim]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: "npm"
      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck
      - run: npm test
